import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import styles from "../styles/Home.module.css";
import { withIronSessionSsr } from "iron-session/next";
import sessionOptions from "../config/session";
import Header from "../components/header";
import useLogout from "../hooks/useLogout";
import { useEffect, useState } from "react";

export const getServerSideProps = withIronSessionSsr(
  async function getServerSideProps({ req }) {
    const user = req.session.user;
    const props = {};
    if (user) {
      props.user = req.session.user;
      props.isLoggedIn = true;
    } else {
      props.isLoggedIn = false;
    }
    return { props };
  },
  sessionOptions
);

export default function Dashboard(props) {
  const router = useRouter();
  const logout = useLogout();

  const [savedMovies, setSavedMovies] = useState([]);
  const [loadingMovies, setLoadingMovies] = useState(true);
  const [moviesError, setMoviesError] = useState("");
  const [movieFilter, setMovieFilter] = useState("all");

  useEffect(() => {
    async function fetchSavedMovies() {
      try {
        setLoadingMovies(true);
        setMoviesError("");

        const response = await fetch("/api/movies");
        const data = await response.json();

        if (!response.ok) {
          throw new Error(data.error || "Failed to load saved movies.");
        }

        setSavedMovies(data || []);
      } catch (error) {
        setMoviesError(
          error.message || "Unable to load movies right now."
        );
      } finally {
        setLoadingMovies(false);
      }
    }

    fetchSavedMovies();
  }, []);

  async function handleStatusChange(movieId, newStatus) {
    try {
      const response = await fetch (`/api/movies/${movieId}`, {
        method: 'PATCH',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ status: newStatus }),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || 'Failed to update status.');
      }

      setSavedMovies((prev) =>
        prev.map((movie) =>
          movie._id === movieId ? { ...movie, status: newStatus } : movie )
      );
    } catch (error) {
      alert(error.message || 'Unable to update status right now.')
    }
  }

  async function handleFavoriteToggle(movieId, currentFavorite) {
  try {
    const response = await fetch(`/api/movies/${movieId}`, {
      method: 'PATCH',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ favorite: !currentFavorite }),
    });

    const data = await response.json();

    if (!response.ok) {
      throw new Error(data.error || 'Failed to update favorite.');
    }

    setSavedMovies((prev) =>
      prev.map((movie) =>
        movie._id === movieId
          ? { ...movie, favorite: !currentFavorite }
          : movie
      )
    );
  } catch (error) {
    alert(error.message || 'Unable to update favorite right now.');
  }
} 
  
  const filteredMovies =
    movieFilter === "favorites"
      ? savedMovies.filter((movie) => movie.favorite)
      : savedMovies;
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header 
        isLoggedIn={props.isLoggedIn} 
        username={props?.user?.username} 
      />

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to a <a href="https://nextjs.org">Next.js!</a> Dashboard Page!
        </h1>

        <p className={styles.description}>
          Current Location: <code className={styles.code}>{router.asPath}</code>
          <br />
          Status:{" "}
          <code className={styles.code}>
            {!props.isLoggedIn && " Not"} Logged In
          </code>
        </p>

        <p className={styles.description}>
          This page is only visible if you are logged in.
        </p>

        <div className={styles.grid}>
          <Link href="/" className={styles.card}>
            <h2>Home &rarr;</h2>
            <p>Return to the homepage.</p>
          </Link>
          <div
            onClick={logout}
            style={{ cursor: "pointer" }}
            className={styles.card}
          >
            <h2>Logout &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </div>
        </div>

        {/* movies section */}
        <section style={{ marginTop: "3rem", width: "100%" }}>
          <h2 className={styles.title}>My Saved Movies</h2>

          {!loadingMovies && !moviesError && savedMovies.length > 0 && (
            <div style={{ marginBottom: "1rem" }}>
              <button
                type="button"
                onClick={() => setMovieFilter("all")}
                style={{
                  marginRight: "0.5rem",
                  fontWeight: movieFilter === "all" ? "bold" : "normal",
                }}
              >
                All Movies
              </button>

              <button
                type="button"
                onClick={() => setMovieFilter("favorites")}
                style={{
                  fontWeight: movieFilter === "favorites" ? "bold" : "normal",
                }}
              >
                Favorites
              </button>
            </div>
          )}

          {loadingMovies && (
            <p className={styles.description}>Loading saved movies...</p>
          )}

          {moviesError && (
            <p className={styles.description}>{moviesError}</p>
          )}

          {!loadingMovies &&
            !moviesError &&
            savedMovies.length === 0 && (
              <p className={styles.description}>
                You have not saved any movies yet.
              </p>
            )}

          {!loadingMovies &&
            !moviesError &&
            savedMovies.length > 0 &&
            filteredMovies.length === 0 && (
              <p className={styles.description}>
                You do not have any favorite movies yet.
              </p>
            )}

          {!loadingMovies &&
            !moviesError &&
            filteredMovies.length > 0 && (
              <div className={styles.grid}>
                {filteredMovies.map((movie) => (
                  <article key={movie._id} className={styles.card}>
                    {movie.posterPath ? (
                      <img
                        src={`https://image.tmdb.org/t/p/w500${movie.posterPath}`}
                        alt={`${movie.title} poster`}
                        width={150}
                        height={225}
                      />
                    ) : (
                      <div>No poster available</div>
                    )}

                    <h3>{movie.title}</h3>

                    <p>
                      {movie.releaseDate || "Release date unavailable"}
                    </p>

                    <label style={{ display: "block", marginTop: "0.5rem" }}>
                      Status:{" "}
                      <select
                        value={movie.status}
                        onChange={(e) =>
                          handleStatusChange(movie._id, e.target.value)
                        }
                      >
                        <option value="want_to_watch">Want to watch</option>
                        <option value="watched">Watched</option>
                        <option value="owned">Owned</option>
                      </select>
                    </label>

                    <button
                      type="button"
                      style={{ marginTop: "0.5rem" }}
                      onClick={() =>
                        handleFavoriteToggle(movie._id, movie.favorite)
                      }
                    >
                      {movie.favorite ? "Unfavorite" : "Favorite"}
                    </button>

                    <p>
                      {movie.overview
                        ? `${movie.overview.slice(0, 120)}${
                            movie.overview.length > 120 ? "..." : ""
                          }`
                        : "No description available."}
                    </p>
                  </article>
                ))}
              </div>
            )}
        </section>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
